#!/usr/bin/env bash

GIT=git

TOKEN_FILE=".token"
NOBODY="NULL"
AUTHOR=$($GIT config --get user.name)

SHOW=false
INIT=false

ADD_LIST=()
DELETE_LIST=()
CLAIM_LIST=()
RELEASE_LIST=()

BRANCH="ignore-this-branch-token-only"
CURRENT_BRANCH="master"

function usage {
  cat << EOF
usage:
$0 <[-h] | [-i] | [-s]
            | [-a <file [file...]>] [-d <file [file...]>] [-c <file [file...]>] [-r <file [file...]>]>
             -a --add:      add token for files
             -c --claim:    claim token for files
             -d --delete:   delete token for files
             -h --help:     help
             -i --init:     init tokens
             -r --release:  release token for files
             -s --show:     show tokens
EOF
  exit 1
}

function set_cmd {
  if [ $# -lt 1 ]
  then
    echo "Error! Missing parameter for set_cmd"
  fi

  if [ ! -z $CURRENT_CMD ]
  then
    case $CURRENT_CMD in
      "add")
        if [ ${#ADD_LIST[@]} -eq 0 ]
        then
          usage
        fi
        ;;
      "claim")
        if [ ${#CLAIM_LIST[@]} -eq 0 ]
        then
          usage
        fi
        ;;
      "delete")
        if [ ${#DELETE_LIST[@]} -eq 0 ]
        then
          usage
        fi
        ;;
      "release")
        if [ ${#RELEASE_LIST[@]} -eq 0 ]
        then
          usage
        fi
        ;;
      *)
        usage
        ;;
    esac
  fi

  CURRENT_CMD=$1
}

function check_init {
  $GIT branch | grep -q $BRANCH
  if [ $? -eq 0 ]
  then
    echo "true"
  else
    $GIT branch -r | grep -q $BRANCH
    if [ $? -eq 0 ]
    then
      $GIT checkout --quiet --track -b $BRANCH origin/$BRANCH
      if [ $? -eq 0 ]
      then
        echo "true"
      fi
    fi
    echo "false"
  fi
}

function stash_if_needed {
  $GIT diff --exit-code --quiet
  res1=$?
  $GIT diff --cached --exit-code --quiet
  res2=$?
  if [ $res1 -ne 0 ] || [ $res2 -ne 0 ]
  then
    $GIT stash --quiet
    echo "true"
  else
    echo "false"
  fi
}

function cpad {
  word=$1
  while [ ${#word} -lt $2 ]
  do
    word="$word$3";
    if [ ${#word} -lt $2 ]
    then
      word="$3$word"
    fi
  done
  echo $word
}

function clean_up {
  $GIT reset --hard HEAD --quiet
  $GIT checkout $CURRENT_BRANCH --quiet

  # stashed
  if $1
  then
    $GIT stash pop --quiet
  fi
}

while [ $# -gt 0 ]
do
  case $1 in
    -a | --add)
      set_cmd "add"
      shift
      continue
      ;;
    -c | --claim)
      set_cmd "claim"
      shift
      continue
      ;;
    -d | --delete)
      set_cmd "delete"
      shift
      continue
      ;;
    -h | --help)
      usage
      ;;
    -i | --init)
      INIT=true
      break
      ;;
    -r | --release)
      set_cmd "release"
      shift
      continue
      ;;
    -s | --show)
      SHOW=true
      break
      ;;
    --) # end of all options
      shift
      break
      ;;
    -* | --*)
      echo "Unknown option: $1"
      usage
      ;;
    *)
      if [ -z $CURRENT_CMD ]
      then
        usage
      fi
      case $CURRENT_CMD in
        "add")
          ADD_LIST+=($1)
          ;;
        "claim")
          CLAIM_LIST+=($1)
          ;;
        "delete")
          DELETE_LIST+=($1)
          ;;
        "release")
          RELEASE_LIST+=($1)
          ;;
        *)
          echo "Error: unkonwn cmd $CURRENT_CMD"
          ;;
      esac
      shift
      ;;
  esac
done

if $INIT
then
  $(check_init) && echo "Error: already initiated!" && exit 1
  STASHED=$(stash_if_needed)
  $GIT branch $BRANCH --quiet
  $GIT checkout $BRANCH --quiet
  printf "%-25s: %-25s: %s\n" $(cpad Filename 25 -) $(cpad Owner 25 -) $(cpad Since 29 -) > $TOKEN_FILE
  $GIT add $TOKEN_FILE
  $GIT commit -m "init token" --quiet
  $GIT push -f origin $BRANCH --quiet
  $GIT checkout $CURRENT_BRANCH --quiet

  if $STASHED
  then
    $GIT stash pop --quiet
  fi
  echo "Initialized token. Now you can add and claim tokens."
  exit 0
fi

if ! $SHOW && [ ${#ADD_LIST[@]} -eq 0 ] && [ ${#DELETE_LIST[@]} -eq 0 ] && [ ${#CLAIM_LIST[@]} -eq 0 ] && [ ${#RELEASE_LIST[@]} -eq 0 ]
then
  usage
fi

if ! $(check_init)
then
  echo "Error: not initialized!" && exit 1
fi

NEED_STASH_POP=false

trap "clean_up $NEED_STASH_POP" 0

NEED_STASH_POP=$(stash_if_needed)
$GIT checkout $BRANCH --quiet
# use the .token file on server as authorative
$GIT pull -f origin $BRANCH --quiet >/dev/null
$GIT merge -s recursive -X theirs $CURRENT_BRANCH --quiet --no-edit >/dev/null

if $SHOW
then
  echo "SHOWING"
  if [ ! -e $TOKEN_FILE ]
  then
    echo "Fatal: .token file does not exist"
    exit 1
  fi
  cat $TOKEN_FILE
  exit 0
fi


# file must exists to be added
for af in ${ADD_LIST[@]}
do
  if [ ! -e $af ]
  then
    echo "Error: cannot add file. File does not exist: $af"
    exit 1
  fi
  egrep -q "^$af\s*:" $TOKEN_FILE
  if [ $? -eq 0 ]
  then
    echo "Token $af already existed" && exit 1
  fi
done

# file must be in .token and user owns the token
# in order to delete or release
for drf in ${DELETE_LIST[@]} ${RELEASE_LIST[@]}
do
  egrep -q "^$drf\s*:\s*$AUTHOR\s*:" $TOKEN_FILE
  if [ $? -ne 0 ]
  then
    echo "Token $drf does not exist or you don't own the token" && exit 1
  fi
done

# file must be in .token and NOBODY owns the token
# in order to claim token
for cf in ${CLAIM_LIST[@]}
do
  egrep -q "^$cf\s*:\s*$NOBODY\s*:" $TOKEN_FILE
  if [ $? -ne 0 ]
  then
    echo "Token $cf already taken by others" && exit 1
  fi
done

# should be safe to add all tokens in list
for af in ${ADD_LIST[@]}
do
  printf "%-25s: %-25s: %s\n" $af "$NOBODY" "$(date)" >> $TOKEN_FILE
done

# should be safe  to delete all tokens in list
for df in ${DELETE_LIST[@]}
do
  sed -i ".bak" "/^$df[[:space:]]*:/d" $TOKEN_FILE
done

# should be safe to claim all tokens in list
for cf in ${CLAIM_LIST[@]}
do
  line=$(printf "%-25s: %-25s: %s" $cf "$AUTHOR" "$(date)")
  sed -i ".bak" "s/$cf[[:space:]]*:[[:space:]]*$NOBODY[[:space:]]*:.*/$line/" $TOKEN_FILE
done

for rf in ${RELEASE_LIST[@]}
do
  # double check the token still exists
  egrep -q "^$rf\s*:" $TOKEN_FILE
  if [ $? -ne 0 ]
  then
    cat $TOKEN_FILE
    echo "Token $rf already deleted!" && exit 1
  fi
  line=$(printf "%-25s: %-25s: %s" $rf "$NOBODY" "$(date)")
  sed -i ".bak" "s/$rf[[:space:]]*:[[:space:]]*$AUTHOR[[:space:]]*:.*/$line/" $TOKEN_FILE
done

$GIT add $TOKEN_FILE

MSG="$AUTHOR"
if [ ${#ADD_LIST[@]} -gt 0 ]
then
  MSG="$MSG adds ${ADD_LIST[@]}"
fi
if [ ${#DELETE_LIST[@]} -gt 0 ]
then
  MSG="$MSG deletes ${DELETE_LIST[@]}"
fi
if [ ${#CLAIM_LIST[@]} -gt 0 ]
then
  MSG="$MSG claims ${CLAIM_LIST[@]}"
fi
if [ ${#RELEASE_LIST[@]} -gt 0 ]
then
  MSG="$MSG releases ${RELEASE_LIST[@]}"
fi

$GIT commit -m "$MSG" --quiet
$GIT push -f origin $BRANCH --quiet

cat $TOKEN_FILE
exit 0
